// Code generated by MockGen. DO NOT EDIT.
// Source: internal/advertisement/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/advertisement/service.go -destination=internal/advertisement/mock/mock_repository_interface.go -package=mockad
//

// Package mockad is a generated GoMock package.
package mockad

import (
	context "context"
	advertisement "marketplace-api/internal/advertisement"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepositoryInterface is a mock of RepositoryInterface interface.
type MockRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryInterfaceMockRecorder
}

// MockRepositoryInterfaceMockRecorder is the mock recorder for MockRepositoryInterface.
type MockRepositoryInterfaceMockRecorder struct {
	mock *MockRepositoryInterface
}

// NewMockRepositoryInterface creates a new mock instance.
func NewMockRepositoryInterface(ctrl *gomock.Controller) *MockRepositoryInterface {
	mock := &MockRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepositoryInterface) EXPECT() *MockRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRepositoryInterface) Create(ctx context.Context, ad *advertisement.Advertisement) (*advertisement.Advertisement, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ad)
	ret0, _ := ret[0].(*advertisement.Advertisement)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryInterfaceMockRecorder) Create(ctx, ad any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepositoryInterface)(nil).Create), ctx, ad)
}

// GetAdvertisementsList mocks base method.
func (m *MockRepositoryInterface) GetAdvertisementsList(ctx context.Context, params *advertisement.AdvertisementListParams) ([]advertisement.AdvertisementList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertisementsList", ctx, params)
	ret0, _ := ret[0].([]advertisement.AdvertisementList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertisementsList indicates an expected call of GetAdvertisementsList.
func (mr *MockRepositoryInterfaceMockRecorder) GetAdvertisementsList(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertisementsList", reflect.TypeOf((*MockRepositoryInterface)(nil).GetAdvertisementsList), ctx, params)
}
